version: "2.1"

services:
  auth:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres
    ports:
      - "3000:3000"
    command: ["npm", "test"]

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tk_auth
      PGDATA: /app/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data: